/* Dữ liệu mẫu ban đầu cho danh sách phiếu mượn */
window.initialBorrows = [
    {
        borrowId: "PM-1001",
        borrowerName: "Nguyễn Văn An",
        bookCode: "BK10001",
        category: "CNTT",
        borrowDate: "2026-05-20",
        dueDate: "2026-06-05",
        phone: "0912345678",
        email: "an.nguyen@library.vn",
        status: "Đang mượn",
        note: "Mượn tài liệu khóa học.",
    },
    {
        borrowId: "PM-1002",
        borrowerName: "Trần Thị Bình",
        bookCode: "BK10025",
        category: "Ngoại ngữ",
        borrowDate: "2026-05-28",
        dueDate: "2026-06-10",
        phone: "0387654321",
        email: "binh.tran@library.vn",
        status: "Đang mượn",
        note: "Chuẩn bị thi tiếng Anh.",
    },
    {
        borrowId: "PM-1003",
        borrowerName: "Lê Văn Cường",
        bookCode: "BK10234",
        category: "Kinh tế",
        borrowDate: "2026-05-10",
        dueDate: "2026-05-25",
        phone: "0791234567",
        email: "cuong.le@library.vn",
        status: "Đã trả",
        note: "Hoàn thành bài tập nhóm.",
    },
    {
        borrowId: "PM-1004",
        borrowerName: "Phạm Thị Dung",
        bookCode: "BK10456",
        category: "Kỹ năng",
        borrowDate: "2026-06-01",
        dueDate: "2026-06-15",
        phone: "0854321098",
        email: "dung.pham@library.vn",
        status: "Đang mượn",
        note: "Tham khảo kỹ năng lãnh đạo.",
    },
    {
        borrowId: "PM-1005",
        borrowerName: "Hoàng Minh Hải",
        bookCode: "BK10789",
        category: "CNTT",
        borrowDate: "2026-05-15",
        dueDate: "2026-05-30",
        phone: "0329876540",
        email: "hai.hoang@library.vn",
        status: "Đã trả",
        note: "Nghiên cứu lập trình web.",
    },
];
